### ISSUE TITLE
Meaning of adding new chain?

### ISSUE THREAD

**Issue by comverser** [safe-global/safe-deployments#211]
The same question has been posted on <https://ethereum.stackexchange.com/questions/147765/adding-a-new-chain-to-the-safe-global-safe-deployments-repository>.

---
I want to deploy the Safe app on a custom EVM-compatible network using [the safe-infrastructure](https://github.com/safe-global/safe-infrastructure) repository. 

What does adding a new chain like [Thundercore Maine](https://github.com/safe-global/safe-deployments/issues/188) to the [safe-deployments](https://github.com/safe-global/safe-deployments) repository mean in this context?

Can I interpret this to mean that I have completed all my work for my purpose and should now wait for the Safe team to complete the remaining related tasks, such as updating libraries that support the custom network for the safe-infrastructure? If so, how long should I generally expect to wait? 

If it is urgent, what actions should I take? Is it necessary to submit a PR to other repositories as shown below besides the safe-deployments repository? What other actions should I take?

- https://github.com/safe-global/safe-core-sdk/
- https://github.com/safe-global/web-core/
- https://github.com/safe-global/safe-eth-py/
- https://github.com/safe-global/safe-config-service/
- https://github.com/safe-global/safe-transaction-service/

**Comment by moisses89** [comment]
Hey @comverser  this project contains a collection of deployments of the Safe contracts. 
Adding your chain here means that is going to be available in safe-deployments package to be used in projects like our web interface https://github.com/safe-global/web-core/blob/dev/package.json#L40 but this doesn't means that after that we are going to support this chain. We currently only support 10 chains, because they need to run an infrastructure for each one.
If you want to run your own infrastructure for your chain you need:
1. deploy the safe contracts in your chain https://github.com/safe-global/safe-contracts#deploy
2. create an issue and PR with your addresses on safe-deployments
3. PR should be provided to safe-eth-py [adding the deployment block number and the address](https://github.com/safe-global/safe-eth-py/blob/master/gnosis/safe/addresses.py) (address will be the same for every network) or you can do it later  using the admin panel going to the Master Copies and Proxy Factories.

On this point you are ready to run your [safe-infrastructure](https://github.com/safe-global/safe-infrastructure) following the guide.

**Comment by iavl** [comment]
> Hey @comverser this project contains a collection of deployments of the Safe contracts. Adding your chain here means that is going to be available in safe-deployments package to be used in projects like our web interface https://github.com/safe-global/web-core/blob/dev/package.json#L40 but this doesn't means that after that we are going to support this chain. We currently only support 10 chains, because they need to run an infrastructure for each one. If you want to run your own infrastructure for your chain you need:
> 
> 1. deploy the safe contracts in your chain https://github.com/safe-global/safe-contracts#deploy
> 2. create an issue and PR with your addresses on safe-deployments
> 3. PR should be provided to safe-eth-py [adding the deployment block number and the address](https://github.com/safe-global/safe-eth-py/blob/master/gnosis/safe/addresses.py) (address will be the same for every network) or you can do it later after run safe-infrastructure using the admin panel for transaction service going to the Master Copies and Proxy Factories.
> 
> On this point you are ready to run your [safe-infrastructure](https://github.com/safe-global/safe-infrastructure) following the guide.

Only when the new release tag is released, can I use the newly added chain, right?

**Comment by Sj-001** [comment]
Hey @moisses89, I created the above two PRs for Neon Devnet and they got merged a few days ago, but when I pulled up the safe-infrastructure, I am recieving the following errors in browser console.
`pageHook.js:12 Uncaught SyntaxError: Invalid regular expression: /^[Î‘-ÏŽ]+$/: Range out of order in character class (at pageHook.js:12:73281)`

`
jector.js:1 Uncaught TypeError: Cannot redefine property: solana
    at Function.defineProperty (<anonymous>)
    at injector.js:1:112381
(anonymous) @ injector.js:1`

`
EthersAdapter.js:112 Uncaught (in promise) Error: Invalid CompatibilityFallbackHandler contract address
    at t.default.getCompatibilityFallbackHandlerContract (EthersAdapter.js:112:19)
    at k (safeContracts.ts:179:21)
    at index.tsx:58:29
    at s (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at P.forEach.e.<computed> [as next] (runtime.js:97:21)
    at r (_async_to_generator.mjs:3:20)
    at s (_async_to_generator.mjs:25:9)
    at _async_to_generator.mjs:32:7
    at new Promise (<anonymous>)
`
