### ISSUE TITLE
Verify Network Address Items Are Sorted

### ISSUE THREAD

**Issue by nlordell** [safe-global/safe-deployments#743]
Currently, the network addresses for a chain can appear as both `["canonical", "eip155"]` or `["eip155", "canonical"]`. Additionally, the networks in the `deployments` field is also not guaranteed to be sorted.

This issue captures the work to ensure both of these JSON elements are in sorted in lexicographical order. There is already a unit test that checks that the network addresses themselves are sorted [here](https://github.com/safe-global/safe-deployments/blob/0fa46dbe3f70c0815a13ead5ce1007b177d474df/src/__tests__/assets.test.ts#L35), so we should:
1. Extend the current test to make sure the values are also sorted
2. Add a new unit test to check that `deployments` field is sorted

**Comment by mmv08** [comment]
Oops, I thought I had documented it. They're sorted by preference for v1 backward compatibility.

So, in v1, we could only have one deployment per network, but in v2, multiple can appear. If we don't keep the sorting, this may lead to our consumers using a different version if the one returned by the v1 function is different:

For example, in v1, it was:
```
1: "canonical"
```
In v2, it can be:
```
2: ["eip155", "canonical"]
```

The v1 function returns the first one in the array so that it would return a different contract address.

**Comment by nlordell** [comment]
Ahhhhh, you had mentioned it, but I forgot it. In that case, we can double-check that this is documented somewhere, and if it is, then close the issue, otherwise document it in a PR and then close the issue.
